import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { ImagesModeDisplayProps } from './types';
import { useImageGeneration } from './useImageGeneration';
import { LoadingState } from './LoadingState';
import { EmptyState } from './EmptyState';
import { ImageGridHeader } from './ImageGridHeader';
import { CustomPromptInput } from './CustomPromptInput';
import { PromptSuggestionsModal } from './PromptSuggestionsModal';
import { ImageCardWithOptions } from './ImageCardWithOptions';
import { InfoCard } from './InfoCard';
import { ArchitectureDiagram } from '../diagrams/ArchitectureDiagram';
import { MindMapDiagram } from '../diagrams/MindMapDiagram';
import { ProcessFlowDiagram } from '../diagrams/ProcessFlowDiagram';
import { ConceptsDiagram } from '../diagrams/ConceptsDiagram';
import { Button } from '@/components/ui/button';
import { RefreshCcw, ArrowLeft } from 'lucide-react';

const ImagesModeDisplay: React.FC<ImagesModeDisplayProps> = ({
  stepId,
  title,
  topic,
  pathId,
}) => {
  const {
    images,
    loading,
    customPrompt,
    setCustomPrompt,
    showPromptInput,
    setShowPromptInput,
    isGeneratingCustom,
    handleGenerateCustomImage,
    handleGenerateImage,
    handleReset,
    completedCount,
    totalCount,
    isGeneratingAny,
    createInitialPrompts,
    currentImageId,
    setCurrentImageId,
  } = useImageGeneration(pathId, topic);

  const [showSuggestionsModal, setShowSuggestionsModal] = useState(false);
  const [activeFallbackDiagram, setActiveFallbackDiagram] = useState<string | null>(null);
  const [showAutoGeneratedSet, setShowAutoGeneratedSet] = useState(false);
  const [isGeneratingLocal, setIsGeneratingLocal] = useState(false);

  // If a specific fallback diagram is active
  if (activeFallbackDiagram) {
    return (
      <div className="max-w-6xl mx-auto px-3 sm:px-4 flex flex-col gap-4">
        <Button 
          variant="ghost" 
          onClick={() => setActiveFallbackDiagram(null)} 
          className="self-start text-brand-purple hover:text-brand-purple/80"
        >
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Visual Options
        </Button>
        {activeFallbackDiagram === 'architecture' && <ArchitectureDiagram topic={topic || 'Topic'} />}
        {activeFallbackDiagram === 'mind_map' && <MindMapDiagram topic={topic || 'Topic'} />}
        {activeFallbackDiagram === 'process_flow' && <ProcessFlowDiagram topic={topic || 'Topic'} />}
        {activeFallbackDiagram === 'concepts' && <ConceptsDiagram topic={topic || 'Topic'} />}
      </div>
    );
  }

  // If auto-generate set is active
  if (showAutoGeneratedSet) {
    if (isGeneratingLocal) {
      return (
        <div className="flex flex-col items-center justify-center p-12 min-h-[400px]">
          <div className="w-12 h-12 border-4 border-brand-purple border-t-transparent rounded-full animate-spin mb-4" />
          <p className="text-gray-600 font-medium">Generating visual set...</p>
        </div>
      );
    }
    
    return (
      <div className="max-w-6xl mx-auto px-3 sm:px-4">
        <div className="flex justify-between items-center mb-6">
          <Button 
            variant="ghost" 
            onClick={() => setShowAutoGeneratedSet(false)} 
            className="text-brand-purple hover:text-brand-purple/80"
          >
            <ArrowLeft className="w-4 h-4 mr-2" /> Back
          </Button>
          <Button 
            variant="outline" 
            onClick={() => {
              setIsGeneratingLocal(true);
              setTimeout(() => setIsGeneratingLocal(false), 800);
            }} 
            className="text-gray-700"
          >
            <RefreshCcw className="w-4 h-4 mr-2" /> Regenerate
          </Button>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pb-12">
          <ArchitectureDiagram topic={topic || 'Topic'} />
          <MindMapDiagram topic={topic || 'Topic'} />
          <ProcessFlowDiagram topic={topic || 'Topic'} />
          <ConceptsDiagram topic={topic || 'Topic'} />
        </div>
      </div>
    );
  }

  if (loading) {
    return <LoadingState />;
  }

  if (images.length === 0) {
    const handleGeneratePrompts = () => {
      // Use our local diagram generator instead of the API to guarantee success
      setIsGeneratingLocal(true);
      setShowAutoGeneratedSet(true);
      setTimeout(() => setIsGeneratingLocal(false), 1200);
    };

    return (
      <>
        <EmptyState
          onGenerateClick={() => setShowSuggestionsModal(true)}
          onGeneratePrompts={handleGeneratePrompts}
          onSelectType={async (typeId) => {
            // Immediately render the specific diagram
            setActiveFallbackDiagram(typeId);
          }}
        />
        <PromptSuggestionsModal
          isOpen={showSuggestionsModal}
          onClose={() => setShowSuggestionsModal(false)}
          onSelectPrompt={async (prompt) => {
            // Map certain prompts to our local diagrams if possible, else use custom
            const p = prompt.toLowerCase();
            if (p.includes('architecture')) { setActiveFallbackDiagram('architecture'); setShowSuggestionsModal(false); }
            else if (p.includes('mind map')) { setActiveFallbackDiagram('mind_map'); setShowSuggestionsModal(false); }
            else if (p.includes('flow')) { setActiveFallbackDiagram('process_flow'); setShowSuggestionsModal(false); }
            else if (p.includes('concept')) { setActiveFallbackDiagram('concepts'); setShowSuggestionsModal(false); }
            else { await handleGenerateCustomImage(undefined, prompt); }
          }}
          topic={topic}
          stepTitle={title}
        />
      </>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="max-w-6xl mx-auto px-3 sm:px-4"
    >
      <ImageGridHeader
        topic={topic}
        completedCount={completedCount}
        totalCount={totalCount}
        isGeneratingAny={isGeneratingAny}
        onGenerateCustom={() => setShowSuggestionsModal(true)}
        onReset={handleReset}
      />

      <PromptSuggestionsModal
        isOpen={showSuggestionsModal}
        onClose={() => setShowSuggestionsModal(false)}
        onSelectPrompt={async (prompt) => {
          await handleGenerateCustomImage(undefined, prompt);
        }}
        topic={topic}
        stepTitle={title}
      />

      {/* Images Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6">
        {images.map((image, index) => (
          <ImageCardWithOptions
            key={image.id}
            image={image}
            index={index}
            onGenerate={(imageId) => {
              handleGenerateImage(images.findIndex(img => img.id === imageId));
            }}
            topic={topic}
            stepTitle={title}
          />
        ))}
      </div>

      <InfoCard title={title} />
    </motion.div>
  );
};

export default ImagesModeDisplay;